queueName: encounters
exchangeName: farpoint
routingKey: key

spring:
  rabbitmq:
    host: docker.for.mac.localhost
    port: 5672
    username: picard
    password: makeitsonumberone
    listener.simple.acknowledge-mode: manual
