logging:
  level: INFO
  loggers:
    com.willhamill: DEBUG

queueConfiguration:
  queueName: encounters
  exchangeName: farpoint
  queueHost: docker.for.mac.localhost
  port: 5672
  timeoutMillis: 3000
  routingKey: key
  user: picard
  # don't use plaintext passwords in config in production obviously
  password: makeitsonumberone

